### ISSUE TITLE
Commits are not pulling

### ISSUE THREAD

**Issue by govconhubby** [pentestfail/TA-Github#1]
Retrieval of commits is failing with error
```GlobalConfigError: Config Not Found for Input```
Log file
```base_modinput.py```

**Comment by pentestfail** [comment]
Sorry its taken me so long to get back with you guys on this! I haven't had a chance to validate if this will break compatibility with Github Enterprise (one of primary use cases originally developed for).  If so then will need to build additional logic to handle and/or parameters be added to the input configuration.
